# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode12.2
env:
  global:
    - WORKSPACE=EasyTipView.xcworkspace
    - FRAMEWORK_NAME=EasyTipView
    - PROJECT=EasyTipView.xcodeproj
    - SCHEME=EasyTipView
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script: xcodebuild -scheme $SCHEME -workspace $WORKSPACE -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' build test
